# Generated by Django 4.0.3 on 2022-05-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=50)),
                ('logo', models.URLField(max_length=300)),
                ('description', models.CharField(max_length=2500)),
                ('mr_close', models.PositiveIntegerField()),
                ('mr_volume', models.PositiveIntegerField()),
                ('market_cap', models.PositiveBigIntegerField()),
            ],
        ),
    ]
