# Generated by Django 4.0.4 on 2022-05-17 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='numStocks',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StockInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bucket')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.stock')),
            ],
        ),
    ]
