# Generated by Django 4.0.3 on 2022-05-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_stock_options_alter_stock_mr_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mr_vol_weighted',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
